spring:
  application:
    client: qpedido
    name: qpedido-order-manager
    version: 0.0.1
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
  flyway:
    schemas: qpedido
    locations: classpath:db/migration/postgresql
    enabled: true

server:
  session:
    timeout: 3600s
    port: ${API_PORT:8090}
  servlet:
    context-path: ${CONTEXT_PATH:/qpedido/order-manager}

feign:
  okhttp:
    enabled: true
  httpclient:
    disableSslValidation: true
    enabled: false